### ISSUE TITLE
A few more papers

### ISSUE THREAD

**Issue by dosumis** [lubianat/what_is_a_cell_type#1]
Bates, Alexander Shakeel, Jasper Janssens, Gregory Sxe Jefferis, and Stein Aerts. 2019. “Neuronal Cell Types in the Fly: Single-Cell Anatomy Meets Single-Cell Genomics.” Current Opinion in Neurobiology 56: 125–34. 

Zeng, Hongkui, and Joshua R. Sanes. 2017. “Neuronal Cell-Type Classification: Challenges, Opportunities and the Path Forward.” Nature Reviews. Neuroscience 18 (9): 530–46. 

Zeng, Hongkui. 2022. “What Is a Cell Type and How to Define It?” Cell 185 (15): 2739–55

Fleck, Jonas Simon, J. Gray Camp, and Barbara Treutlein. 2023. “What Is a Cell Type?” Science 381 (6659): 733–34.

**Comment by lubianat** [comment]
Thanks @dosumis ! I wasn't aware of the Science one, apparently, it is from yesterday!

**Comment by lubianat** [comment]
thank you again, @dosumis! Closing the ticket as completed. 

Also, nice to see you in the acknowledgements of Neuronal cell types in the fly: single-cell anatomy meets single-cell genomics ("We thank D. Osumi-Sutherland for cell type queries of http://virtualflybrain.org,...").
